searchSpace:
  lr0:
    _type: choice    
    _value: [0.0001, 0.0003, 0.001]
  lr1:
    _type: choice
    _value: [0.0001, 0.0003, 0.001]
  # lr0:
  #   _type: choice    
  #   _value: [0.000001, 0.00001, 0.0001]
  # lr1:
  #   _type: choice
  #   _value: [0.000001, 0.00001, 0.0001]
  # kernel_par1:
  #   _type: choice
  #   _value: [0.00000001, 0.0000001, 0.000001, 0.00001]
  # growth_factor:
  #   _type: choice
  #   _value: [1, 2, 3, 4, 5]
  ###########
  # lambda_0:
  #   _type: choice
  #   _value: [0.00000001, 0.0000001, 0.000001, 0.00001]
  # lambda_1:
  #   _type: choice
  #   _value: [0.00000001, 0.0000001, 0.000001, 0.00001]

trialCommand: python3 tune_model.py --epoch 100 --dataset TinyImagenet
trialGpuNumber: 1
trialConcurrency: 2
maxTrialNumber: 20
tuner:
  name: TPE
  classArgs:
    # optimize_mode: minimize
    optimize_mode: maximize
trainingService:  # For other platforms, check mnist-pytorch example
  platform: local
  maxTrialNumberPerGpu: 2
  useActiveGpu: false  # NOTE: Use "true" if you are using an OS with graphical interface (e.g. Windows 10, Ubuntu desktop)
                       # Check the doc for details: https://nni.readthedocs.io/en/latest/reference/experiment_config.html#useactivegpu
